---
name: tasky_mobile_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sample_data:
    git:
      url: git@github.com:iamEtornam/sample_data.git
  flutter_custom_dialog: ^1.3.0
  bot_toast: ^4.0.3
  the_apple_sign_in: ^1.1.1
  cupertino_icons: ^1.0.5
  dotted_border: ^2.0.0+3
  extended_image: ^7.0.2
  firebase_analytics: ^10.1.5
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.1
  firebase_crashlytics: ^3.0.16
  firebase_messaging: ^14.2.6
  flutter_font_icons: ^2.2.5
  flutter_image_stack: ^0.0.6
  flutter_local_notifications: ^13.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.2
  get_it: ^7.2.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  image_cropper: ^3.0.1
  image_picker: ^0.8.6+4
  intl: ^0.18.0
  logger: ^1.2.2
  modal_bottom_sheet: ^3.0.0-pre
  strings: ^0.2.2
  supercharged: ^2.1.1
  textfield_tags: ^2.0.2
  time_ago_provider: ^4.2.0
  readmore: ^2.2.0
  in_app_review: ^2.0.6
  open_apps_settings: ^0.0.4
  package_info_plus: ^3.0.3
  url_launcher: ^6.1.10
  http_parser: ^4.0.2
  path: ^1.8.2
  file: ^6.1.4
  collection: ^1.17.0
  flutter_tawk: ^0.1.0

dependency_overrides:
  path_provider: ^2.0.13
  firebase_storage: ^11.0.15
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/tasky_logo_bg.png
flutter:
  uses-material-design: true
  assets:
    - assets/
