---
name: tasky_mobile_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sample_data:
    git:
      url: git@github.com:iamEtornam/sample_data.git
  flutter_custom_dialog: ^1.3.0
  bot_toast: ^4.1.3
  the_apple_sign_in: ^1.1.1
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  extended_image: ^8.1.1
  firebase_analytics: ^10.6.3
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_crashlytics: ^3.4.3
  firebase_messaging: ^14.7.3
  flutter_font_icons: ^2.2.5
  flutter_image_stack: ^0.0.7
  flutter_local_notifications: ^16.1.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  logger: ^2.0.2+1
  modal_bottom_sheet: ^3.0.0-pre
  strings: ^2.0.3
  supercharged: ^2.1.1
  textfield_tags: ^2.0.2
  time_ago_provider: ^4.2.0
  readmore: ^2.2.0
  in_app_review: ^2.0.8
  open_apps_settings: ^0.0.4
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.1
  http_parser: ^4.0.2
  path: ^1.8.3
  file: ^7.0.0
  collection: ^1.18.0
  flutter_tawk: ^0.1.0

dependency_overrides:
  path_provider: ^2.1.1
  firebase_storage: ^11.4.1
  intl: ^0.18.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/tasky_logo_bg.png
flutter:
  uses-material-design: true
  assets:
    - assets/
